name: make-test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: run tests
        run: npm test
      - name: make setup
        run: make setup
      - name: make test
        run: make test
      - name: make lint
        run: make lint
